### ISSUE TITLE
[MariaThelastttt]geoespacial

### ISSUE THREAD

**Issue by mariadelascotrina** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#1]
https://github.com/mariadelascotrina/03.Geoespacial_Maria.git

**Comment by mariadelascotrina** [comment]
https://github.com/mariadelascotrina/03.Geoespacial_Maria.git

**Comment by mariadelascotrina** [comment]
Perdoncito, este proyecto es un ejemplo de cosas que se deben evitar. Como áreas de mejora entiendo que (i) debería hacer hecho eficiente el código, (ii) hacer incluido las funciones en el src (iii) haber hecho un mapita chulo (iv) hacer un main

y mejorarlo en generaaaaal. Por lo menos ahora sé lo que me falta jejejejejeje

![image](https://user-images.githubusercontent.com/92324979/141836975-f9dabba6-ea9c-4eca-abb4-51aa7f1ec474.png)

**Comment by yamadajc** [comment]
Muy buenas Maria!

Como suelo decir, voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.


##  README

Ese readme esta como que me suena mucho...jejeje. El caso es que ....¿No se te hace raro leer un articulo en un idioma y de repente que cambie a otro?

Me falta sotry telling. Explica un poco como es la empresa que te ha contratado, de esa forma entender mejor los criterios de selección.

En este proyecto hemos realizado muchos pasos, llamadas a la API para sacar información, almacenamiento en mongo, geoqueries, etc. En este caso, podemos incluir una especie de workflow del proyecto.

Por ultimo me gustaria saber mas sobre lo que me voy a encontrar en tu repo. Dejando de lado el nombre, `EL MEJOR.ipynb` ... ¿Qué es? ¿Qué me encontrare allí?

# Estructura del repo

Vamos con la organización del repo que en este caso solo tienes dos archivos pero podríamos haber añadido más para que el repo estuviera más organizado e invitase al lector a indagar. 

Separar cada uno de los pasos del proyecto en distintos jupyters numerados. 

- Un jupyter para sacar la información de la base de datos de companies.

- Un jupyter para hacer llamadas a la API (👀 que no es lo mismo que hacer queries a la API)

- Un jupyter para las geoqueries y el cálculo de las distancias.


# Sintaxis de código

- Se te ha escapado un ```import pandas as pd ``` .

- Haces funciones así que genial. Pero las podrías haber metido en un `.py` y hubieses quedado como una pro.

    ```python
    def devuelvetipoPoint(x):
        return {"type": "Point", "coordinates": [ x["longt"],x["latt"]]}
    ```


- Haces las llamadas a la API para cada ciudad, requerimiento de forma independiente, generas df con la misma estructura o geoqueries que se repiten. Cuando estas repitiendo el código una y otra vez es señal de que tienes que  **HACER FUNCIONES.**

```python
def mis_criterios(criterio:str,ubicacion)
    parametros = {
                        "client_id": client_id,
                        "client_secret": client_secret,
                        "v": "20180323",
                        "ll": f"{ubicacion['coordinates'][1]}, {ubicacion['coordinates'][0]}",
                        "query": criterio
                        }   

    resp = requests.get(url_query, params = parametros).json()


    return list(resp["response"]["venues"])
```

- Has conseguido sacarme las distancias medias de los criterio deseado. Pero tienes que saber que lo que me estas calculando es la distancia media de unas coordenadas en concreto. Osea la distancia media de todos los strabucks a un punto de coordenada concreto `m = {"latt" : 40.41706973493005, "longt": -3.703560607026817}` es de 3.345740. Esto quiere decir que quizás exista alguna oficina en roma con un strabuck mas cercano. 


# ToDo

Trabajas ordenadamente y es de agradecer. Tan solo te diría  que le dieses una vuelta a la atomización de las funciones para dejarlo perfecto. 

Has hecho un buen proyecto. Gracias
