### ISSUE TITLE
[W4-geospatial-data-project] José Díaz

### ISSUE THREAD

**Issue by TheIronhidex** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#15]
https://github.com/TheIronhidex/W4-geospatial-data-project

**Comment by yamadajc** [comment]
Buenos dias Jose!

Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.

A por ello!

# README

EL readme esta perfecto. Veo que te las has apañado bien para no hacer llamadas a APIS o usar la bbdd que companies. Eso si ...¿No podrías haber cambiado aunque sea la foto de portada?😂

# Estructura del repo

- NO tienes el `.gitignore` en tu repo. ¿Donde esta tu `.gitignore`? ¿Y el `.gitignore`? Este archivo es esencial. Debe ser de lo primero que creemos cuando creamos el repo ya que en este fichero vamos a almacenar todos los archivos temporales que se nos crean o aquellos archivos que no queremos que se muestren. 

- Te diría que creases una carpeta de `Notebooks` dividiendo `main.ipynb` en varios cuadernos  los jupyters numerados en el orden que desee que el lector los consuma puede ayudar al orden en nuestro repo.

    > Sugerencia 
    ```
   
    1 - Connection and extraction 
    2 - Analysis
    3 - Geoqueries 
    4 - Map visualization

    ```

- El `main.py` no era necesario pero bien jugado. 

- `portada.jpg`directo a una carpeta `images`

- En la carpeta `datos`veo que se te ha colado un archivo vacío. solamente para que lo sepas. 

## Sintaxis de código

En cuanto a la sintaxis esta bastante bien. Pero te dejo un par de comentarios para que lo mejores. 

- Estarían bien algunos comentarios para los profanos que aterricen en tu repo y deseen aprender de el. Ayudaría a la comunidad. 


- Recuerda que las funciones deben poder ser generalizable. Y si ves que un proceso se repite una y otra vez eso quiere decir que es generalizable. Por ejemplo en `Filtering dataframes by city` podrías crear una función que tome como parámetro la ciudad. 


- Ojo con el docstring… es buena practica e intenta mantener siempre la misma estructura. 

```python
def hacer_cosas():
    ''' Esta función hace cosas.
    args: cosas
    Returns: algo'''
return algo
```
- ¿He visto un geoNear?..._ 🚀 "this is the way" 🚀_

# ToDo
Lo dicho pequeñas cosas que harán grande tu proyecto. 

Felicidades!
