### ISSUE TITLE
[TheCompanyLocator] Fernando Zapico

### ISSUE THREAD

**Issue by 4tolon** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#17]
sin acabar :-(

**Comment by yamadajc** [comment]
Cuando puedas necesito el enlace del proyecto.
Gracias!

**Comment by 4tolon** [comment]
Disculpa Jean, Muchas gracias!

https://github.com/4tolon/TheCompanyLocator

**Comment by yamadajc** [comment]
# Proyecto geoqueries

Hola Fer!
Como siempre digo. Voy a intentar dar todo el feed back posible para que mejores en la medida de lo posible.

Como te dije ayer el proyecto estaba destinado a que demostrarais  vuestras habilidades en el manejo de BBDD no SQL. Y usar métodos como near o GeoNear para calcular distancias para finalmente sacar la mejor localización de nuestra oficina.

Empezamos!!!

##  README
No se muy bien que ha pasado pero el contenido de tu readme no se corresponde con el de tu proyecto. Cuando os damos un ejemplo de readme es  para que os inspiréis, y tengáis una idea de los requisitos que se os piden. Pero no se debe utilizar como plantilla en la que cambiar algunas palabras. Cada proyecto necesita su readme único ya que vuestro proyecto también debería serlo, aunque la temática sea la misma.


## Estructura del repo

Como decía antes, si sigo tu readme, no se muy bien como moverme por tu repo. 

Ojo cuando con los directorios en notebooks se te ha colado un archivo`.json`. En esta carpeta solo debería haber `.ipynb`.

Ten cuidado con el `.gitignore`, parece que se te han colado algunas cosas en varios archivos temporales en ciertos directorios del repo . Recuerda que en el repo solo deberían elementos que queremos que el lector necesite. 



## Sintaxis de código

Tus notebooks tienen muchas cosas interesantes y creativas. Lo que planteas en `Aproximacion.ipynb` con `offices` para luego hacer el `geocode` y sacar las latitudes y longitudes me parece muy buena idea. 

No se muy bien que es lo que necesitabas pero ¿para qué divides en tantos df? Porque no hacerlo de un golpe?

```python 
d1 = slicedic(offices, 0, 21)
df1 = pd.DataFrame.from_dict(d1, orient= 'index', columns = ['adress'])
```

En `OfiMongo.ipynb` me haces una extracción de mongo pero sobre todo companies para luego trabajar via pandas. Como te decía antes el objetivo era que trabajarais con "MongoConsultas".  

Felicidades por haber hecho mapas. Si pinchas [aqui](https://nbviewer.org/) tienes una herramienta que te permite ver los jupyters sin problemas con mapas incluidos. 

Para lo de `geoqueryss.ipynb`te dejo [este tutorial](https://www.youtube.com/watch?v=XyNN9ZAU12s&t=457s)  que te lo explica a la perfeccion. GeoNear nos calcula la distancia entre cada uno de nuestros puntos de nuestra BBDD y nuestras ciudades.

Ojo con los docstring… Mantén la misma estructura siempre.

```python
def hacer_cosas():
    ''' Esta función hace cosas.
    args: cosas
    Returns: algo'''
return algo
```
## ToDo 

Feeeeeeer caguen la leche #TasLiao. Seguro que te suena pero te recomiendo que repliques paso a paso el proyecto de ejemplo de [ana](https://github.com/Ironhack-weekly-Projects/P3_Geospatial_Data) que es de los mejores que he visto. 

Te mando mucha fuerza para lo ultimito que queda porque quiero ver un proyectazo final.
