### ISSUE TITLE
[GeoSpatial Project] Juan Pérez de Ayala

### ISSUE THREAD

**Issue by Juanpda** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#19]
https://github.com/Juanpda/Proyecto_GeoSpatial.git

**Comment by AnaAGG** [comment]
# 📍🗺 Proyecto geoqueries📍🗺

Hola Juan 🙋🏻‍♀️! Seguimos con más proyectos, y ahora es el turno del proyecto de las geoqueries! 

## README
En general el readme esta super bien Juan! Solo te djo por aquí un par de detalles: 

- Por ponerme un poco quisquillosa puedes añadir donde guardas tu datos
- Como haces las geoqueries 

## Estructura del repo

En general esta super bien organizado el repo Juan, buen trabajo. 

- En archivo `src` se te ha pasado un archivo temporal, el `__pycache__`. Recuerda que estos archivos temporales deben ir en el `.gitignore`. 

- Peero super bien que no te hayas dejado los tokens a la vista 👏🏽!

- Tienes varios archivos `json`, lo ideal en este caso es que nos creemos una carpeta que se llame por ejemplo `data` donde vayamos guardando todos los ficheros, tanto `json` como `csv` 

- Lo ideal es que tengamos modularizado el repo en carpetas. En este sentido, podemos crearnos una carpeta que se llame `notebooks` donde guardemos todos los notebooks de nuestro proyecto. Si además numeramos los notebooks para saber el orden de trabajo,s sería TOP. 

- Tienes cosas en ingles y en español, lo ideal es que lo unificaras y lo pusieras todo en el mismo idioma. 


## Sintaxis de código

- Vamos con los *docstrings* de tus funciones. Por convenio, los docstrings van dentro de las funciones. 

    ¿Qué es lo que tiene que tener un docstring?   
            - Qué es lo que hace la función  
            - Qué argumentos recibe  
            - Qué es lo que devuelve  

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Estoy viendo código muy interesante Juan, muy buen trabajo. Te dejo por aquí un detallin por si te aporta valor. 

    En esta función `get_google_nearby_data`, tienes definidos estos dos diccionarios: 

    ```python
    radius = { #Distancia medida en metross
        "train_station":"10000",
        "school":"5000",
        "night_club":"2000",
        "airport":"15000",
        "cafe":"1000"
    }
    ponderations = {
        "train_station":10,
        "school":50,
        "night_club":25,
        "airport":10,
        "cafe":5
    }
    ```
    Cuando nos creamos este tipo de diccionarios lo que normalmente se hace es crearnos otro `.py` a parte donde vamos a ir guardando todos estos diccionarios. Este fichero funcionará como un archivo de configuración y lo llamaremos desde el `.py` donde tenemos las funciones como lo hacemos normalmente. 

- No he visto por ninguna parte como haces las geoqueries. Era parte esencial del proyecto. Meter los datos en una base de datos de mongo y hacer geoqeuries... 


Por el resto poco más Juan, tienes un proyecto impecable. Enhorabuena 🥳


## TODOs

Bueno Juan, te dejo por aquí un pequeño resumen de las cosinas que te dije: 

- Los *docstrings* de las funciones. 
- Puedes crearte un archivo de configuración con los diccionarios que has definido, 
- Meter los datos en mongo y hacer las queries con `Near` o `GeoNear`. 

Venga que ya no queda nadaaaa 🔥

![image](https://user-images.githubusercontent.com/75084991/144639362-1043f204-1a99-48dd-9179-f07b69585682.png)
