### ISSUE TITLE
<<RoBeRtO aLoNsO>> Proyecto Geospatial

### ISSUE THREAD

**Issue by Roblak96** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#2]

**Comment by Roblak96** [comment]
https://github.com/Roblak96/Geospatial-Proyect.git

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Muy buenas Roberto.
como siempre digo, voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.

# README
Como de costumbre el contenido del readme esta correcto. Dejas clarísimo el objetivo del proyecto y el workflow que vas a seguir. Ademas mencionas la tecnología usada con unos
enlaces para seguir a la perfección tu proyecto hubiese estado de 10. 


En tu caso no tienes muchas carpetas, pero en caso de que las tuvieras, recuerda que un pequeño resumen de la estructura del repo, que carpetas tenemos y ficheros nos podemos encontrar.


Te dejo una guía de markdow 👉 [aquí](https://www.markdownguide.org/cheat-sheet/) 


# Estructura del repo
Me siguen faltando ciertas cosas así que te dejo un par de cositas para mejorar de cara al futuro. 

- Sigues teniendo pocos commits y sabes que si un gato te tira el agua sobre el equipo adios proyecto. 

- NO tienes el `.gitignore` en tu repo. ¿Donde esta tu `.gitignore`? ¿Y el `.gitignore`? Este archivo es esencial (debe ser de lo primero que creemos cuando creamos el repo) ya que en este fichero vamos a almacenar todos los archivos temporales que se nos crean o aquellos archivos que no queremos que se muestren. Otra vez, `.ipynb_checkpoints`,un directorio completo que no queremos que se suba. 

- Una carpeta de `Notebooks` con los jupyters numerados en el orden que desee que el lector los consuma puede ayudar al orden en nuestro repo. En él podrías haber metido `Empresas.ipynb` . Por otro lado  `Mapas.ipynb` esta vacío ¿ que paso con este archivo?

# Sintaxis de código 

- Tienes algunos imports en mitad del jupyter. Recuerda, por convenio los imports deben ir al inicio del jupyter, para que cuando empecemos a leer tu código sepamos qué librerías vamos a usar a lo largo del proyecto.


- Veo que has usado a la perfección folium así que bravo por eso. 

- Al final solo podías usar la BBDD de companies, pero no veo rastro de ella por ningún sitio. 

# Feed back
Por problemas con los tokens no has podido realizar el proyecto como nos hubiese gustado; no te preocupes porque lo tendremos en cuenta. Aun así podrías haber hecho un trabajo de consultas en BBDD no SQL. Elegimos mongo no solo por eso sino porque tiene métodos propios que permiten calcular distancias. es el caso de GeoNear nos calcula la distancia entre cada uno de nuestros puntos de nuestra BBDD y nuestras ciudades. Echale un ojo a [esto](https://www.youtube.com/watch?v=XyNN9ZAU12s&t=457s)

Seguro que te suena pero te recomiendo que repliques paso a paso el proyecto de ejemplo de [Ana](https://github.com/Ironhack-weekly-Projects/P3_Geospatial_Data) que es de los mejores que he visto. 


¡¡¡SEGUIMOS!!!
