### ISSUE TITLE
[Ana Walsh] W4-geospatial-data-project

### ISSUE THREAD

**Issue by AnaWalsh** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#25]
https://github.com/AnaWalsh/W4-geospatial-data-project

**Comment by yamadajc** [comment]
# Proyecto geoqueries

Hola Ana!
Como siempre digo. Voy a intentar dar todo el feed back posible para que mejores en la medida de lo posible.

Empezamos!!!

##  README
El readme esta perfect. Eso sí ... de que va la base de datos? Yo no sé de qué va el proyecto cuantame más al respecto. 


## Estructura del repo

La organización de tu repo esta muy bien. 

Ten cuidado con el `.gitignore`, parece que se te han colado algunas cosas en `src`. Recuerda que en el repo solo deberían elementos que queremos que el lector necesite. 

Por otro lado te recomiendo que dediques un tiempo a dividir el jupyter `Geospatial_data_project.ipynb` en cada uno de los pasos del proyecto. Y sí piensas que esta así bien por lo menos mételo en una carpeta notebooks, aunque sea un único archivo es una buena practica. 

 - 1. Find places in each city
 - 2. Geo queries
 - 3. Results



## Sintaxis de código

El código esta super bien. Me faltan algunos docstring en las funciones de tu `api_functions.py`. Genial por hacer funciones propias. OJO recuerda que nuestras funciones tienen que ser genéricas y si ves que algo se repite deberías de poder atomizarlas. Para tus funciones de Madrid, Sevilla y Barcelona podrías haberlas atomizado pasándoles las ciudades como parámetros. 

Lo mismo te diría para `Geospatial_data_project.ipynb` hay cosas que podrías atomizar en funciones. Soy muy pesado, pero sí ves que hay muchas cosas que se repten deberían de agruparlas en una función. Podrías crearte un código que te permita sacara todas las categorías  de una ciudad. 

Otra cosita sobre near es canela pero en mongo tenemos un método que aun mejor. GeoNear nos calcula la distancia entre cada uno de nuestros puntos de nuestra BBDD y nuestras ciudades. Echale un ojo a [esto](https://www.youtube.com/watch?v=XyNN9ZAU12s&t=457s)

notita: `lista = ["Train", "Train", 'Coffee', 'Coffee', 'Coffee', 'Vegan', 'Coffee', 'Coffee','Coffee',"Vegan", 'Coffee', 'Coffee' ]` esto podrias haberlo sacado sin hardcodearlo.


## ToDo 

Recuerda que tenemos que intentar tener todo super organizado para que cuando alguien llegue al repo pueda incluso reproducirlo. Pon unos comentarios en tus jupyters y así quedara todo ready para transmitir tu saber. 

Muy buen trabajo ! 

Pd: cuando puedas refactoriza las funciones a una como build_barcelona_dictionary_list y poner todas las geoqueries en una sola función .
