### ISSUE TITLE
Eduardo Rivera-Proyecto 3

### ISSUE THREAD

**Issue by Eduardo-Rivera98** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#5]
https://github.com/Eduardo-Rivera98/Proyecto_GEO.git

**Comment by yamadajc** [comment]
Hola Eduardo.
Lamentando lo mucho no puedo evaluar este proyecto ya que no hay contenido.

**Comment by yamadajc** [comment]
Muy buenas Edu. 
Como sabes tu proyecto no estaba muy alla. Pero por lo menos he conseguido que no te lo contaran como no entregado😉

Te dejo el  mejor trabajo que hasta la fecha para que le eches un ojo. https://github.com/Ironhack-weekly-Projects/P3_Geospatial_Data
