### ISSUE TITLE
[W4-geospatial-data-project] Daniela Arias

### ISSUE THREAD

**Issue by daniela-arias** [Ironhack-Data-Madrid-Octubre-2021/W4-geospatial-data-project#8]
https://github.com/daniela-arias/Taller_Geo

**Comment by yamadajc** [comment]
# Proyecto Pipeline
Muy buenas Daniela!

Como suelo decir, voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.
¡¡Así que vamos a ello !!

# README

Como siempre has hecho un buen trabajo. Me hablas de los objetivos, la estructura de repositorio y dejas claro cuál va a ser el workflow. Además de nombrar las librerías has incrustado los enlaces. 

# Estructura del repo

Vamos con la organización del repo aun así te dejo un par de cositas para mejorar de cara al futuro. 

- Se te han colado algunas cosas de  `.gitignore`. Con actualizarlo he introducir los que se te han pasado. Recuerda que solo queremos archivos que generen valor al repo. Es posible que subieras un notebook antes del `.gitignore` y así quedarse en cache al hacer push. 

- Podrías haber metido el directorio de  `Json`dentro de `Data`.

- Por cierto creo que también se te ha colado un `.png`en `Data`. 


# Sintaxis de código

- Tienes algunos imports en mitad del jupyter. Recuerda, por convenio los imports deben ir al inicio del jupyter, para que cuando empecemos a leer tu código sepamos qué librerías vamos a usar a lo largo del proyecto.

- Has utilizado near y ese es el camino. Pero en mongo tenemos un método que aun mejor. GeoNear nos calcula la distancia entre cada uno de nuestros puntos de nuestra BBDD y nuestras ciudades. Echale un ojo a [esto](https://www.youtube.com/watch?v=XyNN9ZAU12s&t=457s)

- Ojo con los docstrings.
```python
def hacer_cosas():
    ''' Esta función hace cosas.
    args: cosas
    Returns: algo'''
return algo
```

# Feed back
Has hecho de todo y bien hecho. Podrías ampliar el trabajo  con la BBDD de companies haciendo mas mongo query y asi demostrar mayor dominio sobre este tema. 
Gracias por tu trabajo!
